spring.application.name=tech-user-service

server.port=8001

spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=5A7C3F9D2E6B8A1C4F7D0E3B9A2C5F8D1E4B7A0C3F6D9B2E5A8C1F4D7B0E3A6
jwt.access-token-expiration-ms=900000
jwt.refresh-token-expiration-ms=86400000

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html